---
# this playbook installs but does NOT configure software on a LOCAL DEV machine

- hosts: localhost
  connection: local # not ssh
  become: true # sudo
  vars: # hyphens are not allowed
    scala_repl_version: 2.12.4
  tasks:
    # repositories, keys, aptitude, apt update and upgrade
    - name: aptitude related software is present
      apt: name={{ item }} state=present
      with_items:
        - apt-transport-https
        - aptitude
        - ppa-purge

    - name: apt keys are present 1
      apt_key: keyserver={{item.keyserver}} id={{item.key}} state=present
      with_items:
        - { keyserver: 'hkp://keyserver.ubuntu.com:80', key: '642AC823' } # sbt

    - name: apt keys are present 2
      apt_key: url={{item.url}} state=present
      with_items:
        - { url: 'https://download.sublimetext.com/sublimehq-pub.gpg' } # sublime-text
        - { url: 'https://packages.microsoft.com/keys/microsoft.asc' } # visual-studio-code

    - name: conventional repositories are present
      apt_repository: repo={{ item }} state=present mode="u=rw,g=r,o=r"
      with_items:
        - 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main' # visual-studio-code
        - 'deb https://dl.bintray.com/sbt/debian /' # sbt
        - 'deb https://download.sublimetext.com/ apt/stable/' # sublime-text
        - 'ppa:webupd8team/java' # java

    - name: apt cache and software is up to date
      apt: update_cache=yes upgrade=safe

    # java
    - name: java8 licence is automatically accepted
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: java8 is present
      apt: name={{ item }} state=present # the order is significant
      with_items:
        - oracle-java8-installer
        - oracle-java8-set-default

    - name: java8 is the default alternative (change indication is suppressed)
      command: update-java-alternatives -s java-8-oracle
      changed_when: false

    # debian packages
    - name: debian packages are present
      apt: deb={{ item }} only_upgrade=yes
      with_items:
        - 'http://www.scala-lang.org/files/archive/scala-{{scala_repl_version}}.deb' # scala REPL
        
    # intellij-idea (change indication is suppressed)
    - name: intellij-idea is present
      command: sudo snap install intellij-idea-community --classic
      changed_when: false

    # system monitor
    - name: system monitor is present
      apt: name={{ item }} state=present allow_unauthenticated=yes
      with_items:
        - chrome-gnome-shell
        - gir1.2-clutter-1.0
        - gir1.2-networkmanager-1.0
        - gir1.2-gtop-2.0 
        
    # system monitor hints
    - name: system monitor hints are displayed
      command: echo 'Don't forget to install https://addons.mozilla.org/en-US/firefox/addon/gnome-shell-integration/ and then turn on https://extensions.gnome.org/extension/120/system-monitor/'
      changed_when: false

    # other software
    - name: remaining software is present
      apt: name={{ item }} state=present allow_unauthenticated=yes
      with_items:
        - code
        - curl
        - gnome-tweaks
        - emacs
        - fonts-firacode
        - git
        - guake
        - htop
        - kdiff3
        - mercurial
        - mongodb
        - mosh
        - sbt
        - sublime-text
        - tortoisehg
        - tree
        - unzip
        - vim
        - zip
        - zsh

    # services
    - name: services are running
      service: name={{ item }} state=started enabled=yes
      with_items:
        - mongodb

    # apt cache update and upgrade
    - name: apt cache and software is up to date
      apt: update_cache=yes upgrade=safe
