---
# this playbook installs but does NOT configure software on a LOCAL DEV machine

- hosts: localhost
  connection: local # not ssh
  become: true # sudo
  vars: # hyphens are not allowed
    eclipse_version: 4.4.1
    eclipse_version_with_bells_and_whistles: '{{eclipse_version}}-vfinal-luna-211-20160504'
    mongo_version: 2.6.12
    robomongo_version: 0.8.5
    scala_repl_version: 2.11.8
  tasks:
    # repositories, keys, aptitude, apt update and upgrade
    - name: apt keys are present
      apt_key: keyserver={{item.keyserver}} id={{item.key}} state=present
      with_items:
        - { keyserver: 'hkp://keyserver.ubuntu.com:80', key: '7F0CEB10' } # mongo
        - { keyserver: 'hkp://keyserver.ubuntu.com:80', key: '642AC823' } # sbt

    - name: conventional repositories are present
      apt_repository: repo={{ item }} state=present mode="u=rw,g=r,o=r"
      with_items:
        - 'ppa:indicator-multiload/stable-daily' # indicator-multiload
        - 'ppa:mmk2410/intellij-idea-community' # intellij idea
        - 'ppa:webupd8team/java' # java
        - 'ppa:webupd8team/sublime-text-3' # sublime

    - name: mongo repository is present
      apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present mode="u=rw,g=r,o=r" # mongo

    - name: sbt repository is present
      apt_repository: repo='deb https://dl.bintray.com/sbt/debian /' state=present mode="u=rw,g=r,o=r" # sbt

    - name: aptitude related software is present
      apt: name={{ item }} state=present
      with_items:
        - aptitude
        - ppa-purge

    - name: apt cache and software is up to date
      apt: update_cache=yes upgrade=safe

    # java
    - name: java8 licence is automatically accepted
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: java8 is present
      apt: name={{ item }} state=present # the order is significant
      with_items:
        - python-software-properties
        - oracle-java8-installer
        - oracle-java8-set-default

    - name: java8 is the default alternative (change indication is suppressed)
      command: update-java-alternatives -s java-8-oracle
      changed_when: false

    # debian packages
    - name: debian packages are present
      apt: deb={{ item }} only_upgrade=yes
      with_items:
        - 'http://www.scala-lang.org/files/archive/scala-{{scala_repl_version}}.deb' # scala REPL
        # - 'https://download.robomongo.org/0.8.5/linux/robomongo-{{robomongo_version}}-x86_64.deb' # robomongo

    # eclipse
    - name: eclipse is present
      unarchive: src=http://downloads.typesafe.com/scalaide-pack/{{eclipse_version_with_bells_and_whistles}}/scala-SDK-{{eclipse_version}}-vfinal-2.11-linux.gtk.x86_64.tar.gz dest=/opt copy=no

    # other software
    - name: remaining software is present
      apt: name={{ item }} state=present allow_unauthenticated=yes
      with_items:
        - curl
        - emacs
        - git
        - guake
        - htop
        - indicator-multiload
        - intellij-idea-community
        - kdiff3
        - meld
        - mercurial
        - mongodb-org={{mongo_version}}
        - mosh
        - sbt
        - sublime-text-installer
        - tortoisehg
        - tree
        - unzip
        - vim
        - zip
        - zsh

    # https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-16-04
    - copy: src=mongodb.service dest=/etc/systemd/system/mongodb.service owner=root group=root mode="u=rw,g=r,o=r"

    # services
    - name: services are running
      service: name={{ item }} state=started enabled=yes
      with_items:
        - mongodb

    # apt cache update and upgrade
    - name: apt cache and software is up to date
      apt: update_cache=yes upgrade=safe
